/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BillingAPI": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ChatStreamAPI": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Conversations": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CoreAPI": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Projects": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StorageAPI": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Transactions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserKeys": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "VibeStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}

import "sst"
export {}